import logo from "@/assets/logo.jpeg.asset.json";
import entrance from "@/assets/school-entrance.jpeg.asset.json";
import biology from "@/assets/biology-lab.jpeg.asset.json";
import physics from "@/assets/physics-lab-1.jpeg.asset.json";
import maths from "@/assets/mathmatical-lab-1.jpeg.asset.json";
import playground from "@/assets/play-ground-3.jpeg.asset.json";
import bus from "@/assets/school-bus-1.jpeg.asset.json";
import assembly from "@/assets/school-assembly.jpeg.asset.json";
import yoga from "@/assets/yoga-work-shop.jpeg.asset.json";
import fire from "@/assets/fire-drill-and-activity-2.jpeg.asset.json";
import health from "@/assets/helath-care-med-care-2.jpeg.asset.json";
import firstAid from "@/assets/first-aid-workshop.jpeg.asset.json";
import safety from "@/assets/good-touch-bad-touch-workshop.jpeg.asset.json";
import reception from "@/assets/reception-and-redeptionist.jpeg.asset.json";
import admin from "@/assets/school-administrator-office.jpeg.asset.json";
import director from "@/assets/director.jpeg.asset.json";
import manager from "@/assets/manager.jpeg.asset.json";
import principal from "@/assets/principle.jpeg.asset.json";
import fee from "@/assets/fee-structure.jpeg.asset.json";
export const media = { logo:logo.url, entrance:entrance.url, biology:biology.url, physics:physics.url, maths:maths.url, playground:playground.url, bus:bus.url, assembly:assembly.url, yoga:yoga.url, fire:fire.url, health:health.url, firstAid:firstAid.url, safety:safety.url, reception:reception.url, admin:admin.url, director:director.url, manager:manager.url, principal:principal.url, fee:fee.url };
export const staffImages = Object.values(import.meta.glob("@/assets/staff-*.jpg.asset.json", { eager:true, import:"default" })).map((v:any)=>v.url).sort((a,b)=>Number(a.match(/staff-(\d+)/)?.[1])-Number(b.match(/staff-(\d+)/)?.[1]));
