import { Link, useRouterState } from "@tanstack/react-router";
import { ArrowRight, ChevronDown, ChevronUp, Clock, Mail, MapPin, Menu, Phone, X } from "lucide-react";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { media } from "@/lib/assets";
import { school } from "@/lib/school-data";

const nav = [
  { label: "About", to: "/about", children: [["Our School", "/about"], ["Faculty & Staff", "/faculty"], ["Governance", "/governance"]] },
  { label: "Academics", to: "/academics", children: [["Academic Programme", "/academics"], ["Academic Calendar", "/calendar"], ["School Timings", "/timings"], ["Fee Structure", "/fees"]] },
  { label: "Campus", to: "/facilities", children: [["Facilities", "/facilities"], ["Activities", "/activities"], ["School Houses", "/houses"], ["Gallery", "/gallery"]] },
  { label: "Information", to: "/notices", children: [["Notices", "/notices"], ["Holidays", "/holidays"], ["Emergency Contacts", "/emergency"], ["Downloads", "/downloads"]] },
  { label: "Contact", to: "/contact" },
] as const;

export function SiteShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const [desktopOpen, setDesktopOpen] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<string | null>(null);
  const menuRef = useRef<HTMLElement>(null);
  const path = useRouterState({ select: (s) => s.location.pathname });
  useEffect(() => { setOpen(false); setDesktopOpen(null); }, [path]);
  useEffect(() => {
    const close = (event: MouseEvent) => { if (!menuRef.current?.contains(event.target as Node)) setDesktopOpen(null); };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, []);
  return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
    <div className="bg-gold text-brand"><div className="mx-auto flex min-h-9 max-w-7xl items-center justify-between gap-4 px-5 text-xs font-bold"><span>Admissions open · Session {school.session}</span><a href={`tel:${school.phone}`} className="flex items-center gap-2"><Phone className="size-3.5"/> {school.phone}</a></div></div>
    <header className="sticky top-0 z-50 border-b border-border/70 bg-background/95 backdrop-blur-xl">
      <div className="mx-auto flex h-[76px] max-w-7xl items-center gap-5 px-4 sm:px-6">
        <Link to="/" className="flex min-w-0 flex-1 items-center gap-3 xl:flex-none"><img src={media.logo} className="size-12 shrink-0 rounded-sm object-contain" alt="Golden Future International School crest"/><div className="min-w-0"><strong className="block truncate font-display text-base text-brand sm:text-lg">Golden Future</strong><span className="block truncate text-[9px] font-bold uppercase tracking-[.18em] text-muted-foreground">International School</span></div></Link>
        <nav ref={menuRef} className="ml-auto hidden items-center gap-0.5 xl:flex" aria-label="Main navigation"><Link to="/" className="nav-link" activeProps={{className:"nav-active"}}>Home</Link>{nav.map(item => <div className="relative" key={item.label} onMouseEnter={() => "children" in item && setDesktopOpen(item.label)} onMouseLeave={() => setDesktopOpen(null)}>{"children" in item ? <div className="flex items-center"><Link to={item.to} className="nav-link pr-1" activeProps={{className:"nav-active"}}>{item.label}</Link><Button variant="ghost" size="icon" className="size-8" aria-label={`Open ${item.label} menu`} aria-expanded={desktopOpen===item.label} aria-haspopup="menu" onClick={() => setDesktopOpen(desktopOpen===item.label?null:item.label)}><ChevronDown className={`size-3.5 transition-transform ${desktopOpen===item.label?"rotate-180":""}`}/></Button></div> : <Link to={item.to} className="nav-link" activeProps={{className:"nav-active"}}>{item.label}</Link>}{"children" in item && desktopOpen===item.label && <div className="absolute left-0 top-full w-60 pt-3"><div className="border-t-2 border-gold bg-popover p-2 shadow-menu" role="menu">{item.children.map(c=><Link key={c[0]} to={c[1]} className="block border-b border-border/60 px-4 py-3 text-sm font-semibold text-popover-foreground transition-colors last:border-0 hover:bg-accent hover:text-brand" role="menuitem">{c[0]}</Link>)}</div></div>}</div>)}</nav>
        <Button asChild className="hidden lg:flex"><Link to="/admissions">Apply now <ArrowRight/></Link></Button>
        <Button variant="ghost" size="icon" className="xl:hidden" aria-label={open?"Close menu":"Open menu"} aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</Button>
      </div>
      {open&&<nav className="animate-slide-down max-h-[calc(100vh-110px)] overflow-y-auto border-t border-border bg-background px-5 py-4 xl:hidden" aria-label="Mobile navigation"><Link to="/" className="mobile-link">Home</Link>{nav.map(item=><div key={item.label} className="border-b border-border"><div className="grid grid-cols-[1fr_auto] items-center"><Link to={item.to} className="mobile-link border-0">{item.label}</Link>{"children" in item&&<Button variant="ghost" size="icon" aria-label={`Toggle ${item.label} links`} aria-expanded={expanded===item.label} onClick={()=>setExpanded(expanded===item.label?null:item.label)}><ChevronDown className={`transition-transform ${expanded===item.label?"rotate-180":""}`}/></Button>}</div>{"children" in item&&expanded===item.label&&<div className="mb-3 border-l-2 border-gold pl-4">{item.children.map(c=><Link key={c[0]} to={c[1]} className="block py-2.5 text-sm font-semibold text-muted-foreground">{c[0]}</Link>)}</div>}</div>)}<Button asChild className="mt-5 w-full"><Link to="/admissions">Admission enquiry</Link></Button></nav>}
    </header>
    <main>{children}</main><Footer/><ScrollTop/>
  </div>;
}

function ScrollTop(){const [show,setShow]=useState(false);useEffect(()=>{const f=()=>setShow(scrollY>500);addEventListener("scroll",f,{passive:true});return()=>removeEventListener("scroll",f)},[]);return show?<Button size="icon" className="fixed bottom-5 right-5 z-40 size-11 rounded-full shadow-xl" aria-label="Scroll to top" onClick={()=>scrollTo({top:0,behavior:"smooth"})}><ChevronUp/></Button>:null}
function Footer(){return <footer className="bg-brand text-brand-foreground"><div className="mx-auto max-w-7xl px-5 py-16"><div className="grid gap-12 md:grid-cols-2 lg:grid-cols-4"><div><img src={media.logo} alt="GFIS crest" className="size-20 rounded-sm bg-background object-contain p-1"/><h2 className="mt-5 font-display text-2xl">Golden Future International School</h2><p className="mt-4 text-sm leading-7 text-brand-foreground/70">CBSE · English Medium · Co-Educational<br/>Nursery to Class 12</p></div><FooterLinks title="Explore" links={[["About","/about"],["Academics","/academics"],["Faculty","/faculty"],["Facilities","/facilities"],["Activities","/activities"]]}/><FooterLinks title="Information" links={[["Admissions","/admissions"],["Fee Structure","/fees"],["School Timings","/timings"],["Holiday List","/holidays"],["Emergency","/emergency"]]}/><div><p className="footer-title">Contact</p><ul className="mt-5 space-y-4 text-sm leading-6 text-brand-foreground/70"><li className="flex gap-3"><MapPin className="mt-1 size-4 shrink-0 text-gold"/>{school.address}</li><li><a className="flex gap-3" href={`tel:${school.phone}`}><Phone className="size-4 text-gold"/>{school.phone}</a></li><li className="flex gap-3"><Clock className="size-4 text-gold"/>Summer {school.summer}</li><li className="flex gap-3"><Mail className="size-4 text-gold"/>{school.website}</li></ul></div></div><div className="mt-12 flex flex-col gap-3 border-t border-brand-foreground/15 pt-7 text-xs text-brand-foreground/50 sm:flex-row sm:justify-between"><p>© 2026 Golden Future International School. All rights reserved.</p><p>Patiyali · Kasganj · Uttar Pradesh</p></div></div></footer>}
function FooterLinks({title,links}:{title:string,links:readonly (readonly [string,string])[]}){return <div><p className="footer-title">{title}</p><ul className="mt-5 space-y-3 text-sm">{links.map(l=><li key={l[0]}><Link to={l[1]} className="text-brand-foreground/70 transition-colors hover:text-gold">{l[0]}</Link></li>)}</ul></div>}
export function PageHero({eyebrow,title,description,image=media.entrance}:{eyebrow:string,title:string,description:string,image?:string}){return <section className="relative overflow-hidden bg-brand"><div className="absolute inset-0"><img src={image} alt="" className="h-full w-full object-cover object-center opacity-35"/><div className="absolute inset-0 bg-hero-overlay"/></div><div className="relative mx-auto max-w-7xl px-5 py-20 sm:py-28"><p className="eyebrow">{eyebrow}</p><h1 className="mt-4 max-w-4xl font-display text-4xl font-semibold leading-tight text-brand-foreground sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-8 text-brand-foreground/75 sm:text-lg">{description}</p></div></section>}
export function SectionHead({eyebrow,title,text,light=false}:{eyebrow:string,title:string,text?:string;light?:boolean}){return <div className="max-w-2xl"><p className="eyebrow">{eyebrow}</p><h2 className={`mt-3 font-display text-3xl font-semibold leading-tight sm:text-5xl ${light?"text-brand-foreground":"text-brand"}`}>{title}</h2>{text&&<p className={`mt-5 leading-8 ${light?"text-brand-foreground/70":"text-muted-foreground"}`}>{text}</p>}</div>}
export function CTA(){return <section className="bg-gold"><div className="mx-auto grid max-w-7xl items-center gap-7 px-5 py-12 md:grid-cols-[1fr_auto]"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-brand">Admissions {school.session}</p><h2 className="mt-2 font-display text-3xl font-semibold text-brand sm:text-4xl">Begin your child’s Golden Future.</h2><p className="mt-3 text-brand/75">Admissions are open from Nursery to Class 12.</p></div><Button asChild size="lg" className="bg-brand text-brand-foreground hover:bg-brand/90"><Link to="/admissions">Admission enquiry <ArrowRight/></Link></Button></div></section>}
export const seo=(title:string,description:string,path:string)=>({meta:[{title:`${title} — Golden Future International School`},{name:"description",content:description},{property:"og:title",content:`${title} — Golden Future International School`},{property:"og:description",content:description},{property:"og:type",content:"website"},{property:"og:url",content:path},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:path}]});