import { Link, useRouterState } from "@tanstack/react-router";
import { ChevronDown, Menu, X, ArrowRight, Phone, MapPin, Clock, Mail, ChevronUp } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { media } from "@/lib/assets";
import { school } from "@/lib/school-data";
const nav = [
 {label:"About",to:"/about",children:[["About School","/about"],["Leadership","/about"],["Governance","/governance"]]},
 {label:"Academics",to:"/academics",children:[["Academic Programme","/academics"],["Calendar","/calendar"],["School Timings","/timings"],["Fee Structure","/fees"]]},
 {label:"Campus",to:"/facilities",children:[["Facilities","/facilities"],["Activities","/activities"],["School Houses","/houses"],["Gallery","/gallery"]]},
 {label:"Information",to:"/notices",children:[["Notices","/notices"],["Holidays","/holidays"],["Emergency Contacts","/emergency"],["Downloads","/downloads"]]},
 {label:"Faculty",to:"/faculty"},{label:"Contact",to:"/contact"}
] as const;
export function SiteShell({children}:{children:ReactNode}) {
 const [open,setOpen]=useState(false); const [expanded,setExpanded]=useState<string|null>(null); const path=useRouterState({select:s=>s.location.pathname});
 useEffect(()=>setOpen(false),[path]);
 return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
  <div className="bg-brand px-4 py-2 text-brand-foreground"><div className="mx-auto grid max-w-7xl grid-cols-[minmax(0,1fr)_auto] items-center gap-4 text-xs"><span className="truncate font-semibold">Admissions Open · Session 2026–27</span><a href={`tel:${school.phone}`} className="flex shrink-0 items-center gap-1.5"><Phone className="size-3.5"/> {school.phone}</a></div></div>
  <header className="sticky top-0 z-50 border-b border-glass bg-glass/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between gap-5 px-4 sm:px-6">
   <Link to="/" className="flex min-w-0 items-center gap-3"><img src={media.logo} className="size-14 shrink-0 rounded-lg object-cover" alt="Golden Future International School crest"/><div className="min-w-0"><strong className="block truncate font-display text-sm text-brand sm:text-base">Golden Future International School</strong><span className="block truncate text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Patiyali · Kasganj</span></div></Link>
   <nav className="hidden items-center gap-1 xl:flex" aria-label="Main navigation"><Link to="/" className="nav-link">Home</Link>{nav.map(item=><div className="group relative" key={item.label}><Link to={item.to} className="nav-link flex items-center gap-1">{item.label}{"children" in item&&<ChevronDown className="size-3.5"/>}</Link>{"children" in item&&<div className="invisible absolute left-0 top-full min-w-56 translate-y-2 rounded-lg border border-border bg-popover p-2 opacity-0 shadow-xl transition-all group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:translate-y-0 group-focus-within:opacity-100">{item.children.map(c=><Link key={c[0]} to={c[1]} className="block rounded-md px-3 py-2.5 text-sm text-popover-foreground hover:bg-accent">{c[0]}</Link>)}</div>}</div>)}</nav>
   <div className="hidden shrink-0 items-center gap-2 sm:flex"><Link to="/admissions" className="btn-primary">Admissions <span className="hidden lg:inline">2026–27</span></Link></div>
   <button className="icon-button xl:hidden" aria-label={open?"Close menu":"Open menu"} aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button>
  </div>{open&&<nav className="animate-slide-down border-t border-border bg-popover px-4 py-4 xl:hidden" aria-label="Mobile navigation"><Link to="/" className="mobile-link">Home</Link>{nav.map(item=><div key={item.label} className="border-b border-border"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center"><Link to={item.to} className="mobile-link border-0">{item.label}</Link>{"children" in item&&<button className="icon-button" onClick={()=>setExpanded(expanded===item.label?null:item.label)} aria-label={`Toggle ${item.label} links`}><ChevronDown className={`size-4 transition-transform ${expanded===item.label?"rotate-180":""}`}/></button>}</div>{"children" in item&&expanded===item.label&&<div className="mb-3 ml-4 border-l border-gold/40 pl-3">{item.children.map(c=><Link key={c[0]} to={c[1]} className="block py-2.5 text-sm text-muted-foreground">{c[0]}</Link>)}</div>}</div>)}<Link to="/admissions" className="btn-primary mt-4 w-full">Admission Enquiry</Link></nav>}</header>
  <main>{children}</main><Footer/><ScrollTop/>
 </div>
}
function ScrollTop(){const [show,setShow]=useState(false);useEffect(()=>{const f=()=>setShow(scrollY>500);addEventListener("scroll",f,{passive:true});return()=>removeEventListener("scroll",f)},[]);return show?<button className="fixed bottom-5 right-5 z-40 grid size-11 place-items-center rounded-full bg-brand text-brand-foreground shadow-lg" aria-label="Scroll to top" onClick={()=>scrollTo({top:0,behavior:"smooth"})}><ChevronUp/></button>:null}
function Footer(){return <footer className="bg-brand text-brand-foreground"><div className="mx-auto max-w-7xl px-5 py-14"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-4"><div><img src={media.logo} alt="GFIS crest" className="size-20 rounded-xl object-cover"/><h2 className="mt-4 font-display text-xl font-bold">Golden Future International School</h2><p className="mt-3 text-sm leading-6 text-brand-foreground/70">English Medium · CBSE · Co-Educational<br/>Learn. Lead. Make a Difference.</p></div><FooterLinks title="Explore" links={[["About","/about"],["Academics","/academics"],["Faculty","/faculty"],["Facilities","/facilities"],["Activities","/activities"]]}/><FooterLinks title="Information" links={[["Admissions","/admissions"],["Fee Structure","/fees"],["School Timings","/timings"],["Holiday List","/holidays"],["Emergency","/emergency"]]}/><div><p className="footer-title">Contact</p><ul className="mt-4 space-y-3 text-sm text-brand-foreground/70"><li className="flex gap-2"><MapPin className="mt-0.5 size-4 shrink-0 text-gold"/>{school.address}</li><li><a className="flex gap-2" href={`tel:${school.phone}`}><Phone className="size-4 text-gold"/>{school.phone}</a></li><li className="flex gap-2"><Clock className="size-4 text-gold"/>Summer {school.summer}</li></ul></div></div><div className="mt-12 flex flex-col gap-2 border-t border-brand-foreground/15 pt-6 text-xs text-brand-foreground/50 sm:flex-row sm:justify-between"><p>© 2026 Golden Future International School. All rights reserved.</p><p>Nursery to Class 12 · Patiyali, Kasganj</p></div></div></footer>}
function FooterLinks({title,links}:{title:string,links:readonly (readonly [string,string])[]}){return <div><p className="footer-title">{title}</p><ul className="mt-4 space-y-2.5 text-sm">{links.map(l=><li key={l[1]}><Link to={l[1]} className="text-brand-foreground/70 hover:text-gold">{l[0]}</Link></li>)}</ul></div>}
export function PageHero({eyebrow,title,description,image=media.entrance}:{eyebrow:string,title:string,description:string,image?:string}){return <section className="page-hero"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-14 md:grid-cols-12 md:py-20"><div className="animate-fade-in md:col-span-7"><p className="eyebrow">{eyebrow}</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-bold leading-tight text-brand sm:text-5xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">{description}</p></div><div className="md:col-span-5"><img src={image} alt="Golden Future International School" className="h-72 w-full rounded-2xl object-cover shadow-xl md:h-80"/></div></div></section>}
export function SectionHead({eyebrow,title,text}:{eyebrow:string,title:string,text?:string}){return <div className="max-w-2xl"><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 font-display text-3xl font-bold leading-tight text-brand sm:text-4xl">{title}</h2>{text&&<p className="mt-4 leading-7 text-muted-foreground">{text}</p>}</div>}
export function CTA(){return <section className="bg-soft"><div className="mx-auto max-w-7xl px-5 py-16"><div className="grid items-center gap-6 rounded-2xl border border-glass bg-glass p-7 shadow-soft md:grid-cols-[minmax(0,1fr)_auto] md:p-10"><div><p className="eyebrow">Admissions 2026–27</p><h2 className="mt-2 font-display text-3xl font-bold text-brand">Begin your child’s journey with GFIS.</h2><p className="mt-3 text-muted-foreground">Admissions are open from Nursery to Class 12.</p></div><Link to="/admissions" className="btn-primary">Admission Enquiry <ArrowRight className="size-4"/></Link></div></div></section>}
export const seo=(title:string,description:string,path:string)=>({meta:[{title:`${title} — Golden Future International School`},{name:"description",content:description},{property:"og:title",content:`${title} — Golden Future International School`},{property:"og:description",content:description},{property:"og:type",content:"website"},{property:"og:url",content:path},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:path}]});
